# =========================
# Configuration mensuelle
# =========================

# Label du mois (optionnel, juste pour les logs)
month_label: "2025-09"

# Chemins relatifs à la racine du projet
input_html: "misenpageur/fichier_biduleur/biduleur_bullets.html"   # fichier HTML source
template_pdf: "misenpageur/templates/bidul_template.pdf"  # gabarit optionnel (non utilisé en sortie ici)
output_pdf: "misenpageur/bidul/bidul_prototype.pdf"      # chemin du PDF généré

logos_dir: "misenpageur/assets/logos"   # dossier contenant jusqu'à 10 logos
cover_image: "misenpageur/assets/couv/couverture.png"  # image de couverture
ours_md: "misenpageur/assets/ours/ours.md"   # fichier texte constant (ours)

# =========================
# Paramètres typographiques
# =========================

# Police utilisée (assure-toi que ArialNarrow est installée et déclarée dans ReportLab,
# sinon change pour Helvetica ou Liberation Sans Narrow)
font_name: "Arial Narrow"

# Taille de police : min/max autorisées pour le shrink
font_size_min: 5
font_size_max: 12.0

# Ratio entre taille et interligne (leading = font_size * leading_ratio)
leading_ratio: 1.12

# =========================
# Marges internes
# =========================

# Pour ne PAS avoir de marge → 0
inner_padding: 2

# =========================
# Répartition du texte HTML
# =========================

# Ordre d’alimentation des sections texte
# (attention: le rendu final est en 2 pages :
#  page 1 = S1,S2,S3,S4 ; page 2 = S5,S6,S7,S8)
text_sections_order:
  - "S5"
  - "S6"
  - "S3"
  - "S4"

# Espacement (pt)
date_spaceBefore: 4
date_spaceAfter: 4

event_spaceBefore: 1
event_spaceAfter: 1

event_spaceAfter_perLine: 0.4
min_event_spaceAfter: 1
# Spécifique à S5 : pas de marge avant pour la 1re ligne non-événement (ex. "En bref")
first_non_event_spaceBefore_in_S5: 0

# Césure utile
split_min_gain_ratio: 0.10 # n’autoriser la césure A→B que si elle comble ≥10% de la hauteur de la section A (et ≥1 ligne)

# Bullets / hanging indent
show_event_bullet: true
event_bullet_replacement: null
event_hanging_indent: 10

# Date box (bloc)
date_box:
  enabled: false
  padding: 3
  border_width: 0
  border_color: "#000000"
  back_color: "#f2f2f2"

# Configuration de la ligne horizontale pour les dates (Jeudi 25, etc.)
date_line:
  enabled: true       # Mettre à true pour afficher la ligne, false pour la cacher
  width: 1.3         # Épaisseur de la ligne en points (0.5 est fin)
  color: "#000000"    # Couleur de la ligne au format hexadécimal
  gap_after_text_mm: 3.0

auteur_couv: ""
auteur_couv_url: ""

# Qualité impression / prépresse
prepress:
  convert_images: false          # Convertir les images en CMYK avant insertion
  jpeg_quality: 95              # Qualité JPEG lors de la conversion (85–100)
  min_effective_dpi: 300        # Alerte si l'image descend sous ce DPI
  max_effective_dpi: 450        # (optionnel) Surdimension > ce DPI -> on peut réduire (pour le poids)
  cmyk_profile: ""              # (optionnel) ICC CMYK pour une meilleure conversion (ex: "CoatedFOGRA39.icc")

  add_crop_marks: false          # Tracer des traits de coupe
  bleed_mm: 0                   # Fond perdu (mm) pour la page (cosmétique des repères visuels)

  # Post-traitement PDF/X via Ghostscript (facultatif, avancé)
  pdfx: false                   # true -> tente une conversion PDF/X-1a
  ghostscript_path: "gswin64c"  # Chemin `gswin64c` (Windows) ou `gs` (macOS/Linux)
  pdfx_icc: ""                  # ICC de sortie (ex: ISOcoated_v2_300_eci.icc) si pdfx:true

s1_split:
  logos_ratio: 0.5
  gutter: 6            # (optionnel) gouttière verticale entre logos et ours

pdf_layout:
  page_margin_mm: 1 # Marge globale sur la page A4, en millimètres
  section_spacing_mm: 1 # Espacement entre les sections A5, si désiré

section_1:
  # Configuration de la colonne "Ours"
  ours_font_name: "Arial"      # Police de l'ours
  ours_font_size: 7.0            # Taille de la police de l'ours
  ours_line_spacing: 1.3       # Interlignage (ex: 1.2 = 120%)
  # Configuration titre du QR code
  qr_code_title: "Agenda culturel"
  qr_code_title_font_name: "Arial-Bold"
  qr_code_title_font_size: 9

  # Configuration du QR Code
  qr_code_value: "https://www.lebidul.com" # L'URL ou le texte du QR code
  qr_code_height_mm: 30        # Hauteur (et largeur) du QR code en mm

  # Configuration de la colonne "Logos"
  additional_box_height_mm: 35 # Hauteur de la "boîte additionnelle" sous les logos
  logo_box_bottom_margin_mm: 0 # Marge entre la zone des logos et la boîte additionnelle

# Impression facultative de la section de couverture
skip_cover: false

poster:
  enabled: true
  title: "L'AGENDA COMPLET"
  font_name_title: "Helvetica-Bold"
  font_size_title: 32.0
  # Tailles de police pour le corps du texte du poster
  font_size_min: 6.0
  font_size_max: 10.0