# Define your constants here
DATE = 'date'
GENRE_EVT = 'genre'
HORAIRE = 'horaire'
FESTIVAL = 'festival'
STYLE_FESTIVAL = 'style_festival'
VILLE = 'ville'
LIEU = 'lieu'
PRIX = 'prix'
GENRE_EVT_SV = 'sv'
GENRE_EVT_CONCERT = 'concert'
SPECTACLE1 = 'spectacle1'
ARTISTE1 = 'artiste1'
STYLE1 = 'style1'
SPECTACLE2 = 'spectacle2'
ARTISTE2 = 'artiste2'
STYLE2 = 'style2'
SPECTACLE3 = 'spectacle3'
ARTISTE3 = 'artiste3'
STYLE3 = 'style3'
SPECTACLE4 = 'spectacle4'
ARTISTE4 = 'artiste4'
STYLE4 = 'style4'
LIEN1 = 'lien1'
LIEN2 = 'lien2'
LIEN3 = 'lien3'
LIEN4 = 'lien4'
OUTPUT_FOLDER_NAME = './outputs/'
P_MD_OPEN_DATE = '<p class="date">'
P_MD_CLOSE_DATE = '</p>'
P_MD_OPEN_DATE_AGENDA = '<p class="date-agenda">'
P_MD_CLOSE = '</p>'
P_MD_OPEN = '<p>'
P_MD_POST_OPEN = '<div class="post">'
