name: Build and Release - Biduleur (moulinette)

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Numéro de version (ex: 1.0.0)'
        required: true
        default: '1.0.0'
      publish_release:
        description: 'Publier la release ?'
        required: true
        default: 'false'
        type: choice
        options: ['true','false']

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install build tooling
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install pyinstaller==6.6.0 pyinstaller-hooks-contrib

      - name: Install project dependencies
        run: |
          pip install -r biduleur/requirements.txt

      - name: Sanity-check deps
        run: |
          python -c "import sys; print(sys.version)"
          pip show pandas || (echo pandas missing && exit /b 1)
          pip show numpy  || (echo numpy missing  && exit /b 1)

      - name: Build with PyInstaller
        run: |
          pyinstaller biduleur.spec --clean --workpath build --distpath dist

#      - name: Inspect dist (debug)
#        run: |
#          dir dist
#          dir dist\biduleur
#          IF EXIST dist\biduleur\_internal\Lib\site-packages\pandas (dir dist\biduleur\_internal\Lib\site-packages\pandas) ELSE (echo "pandas folder not found in bundle")

      - name: Package ZIP
        run: |
          mkdir release_assets
          echo "Biduleur ${{ github.event.inputs.version || github.ref_name }}" > dist\biduleur\README.txt
          echo "================================================" >> dist\biduleur\README.txt
          echo "" >> dist\biduleur\README.txt
          echo "Merci d'utiliser Biduleur !" >> dist\biduleur\README.txt
          echo "" >> dist\biduleur\README.txt
          echo "INSTRUCTIONS:" >> dist\biduleur\README.txt
          echo "1. Extrayez le contenu de ce fichier ZIP dans un dossier de votre choix." >> dist\biduleur\README.txt
          echo "2. Double-cliquez sur biduleur.exe pour lancer l'application." >> dist\biduleur\README.txt
          echo "3. Suivez les instructions à l'écran." >> dist\biduleur\README.txt
          echo "" >> dist\biduleur\README.txt
          echo "REQUIREMENTS:" >> dist\biduleur\README.txt
          echo "- Windows 10 ou supérieur" >> dist\biduleur\README.txt
          echo "- Aucune installation supplémentaire nécessaire" >> dist\biduleur\README.txt
          echo "" >> dist\biduleur\README.txt
          echo "SUPPORT:" >> dist\biduleur\README.txt
          echo "Pour toute question ou problème, contactez-nous via GitHub." >> dist\biduleur\README.txt
          Compress-Archive -Path dist\biduleur\* -DestinationPath release_assets\biduleur-${{ github.event.inputs.version || github.ref_name }}-windows.zip -Force

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: biduleur-${{ github.event.inputs.version || github.ref_name }}-windows
          path: release_assets\biduleur-${{ github.event.inputs.version || github.ref_name }}-windows.zip

      - name: Create Release
        if: ${{ github.event.inputs.publish_release != 'false' && (github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/')) }}
        uses: softprops/action-gh-release@v2
        with:
          name: Biduleur ${{ github.event.inputs.version || github.ref_name }}
          tag_name: ${{ github.event.inputs.version && format('v{0}', github.event.inputs.version) || github.ref_name }}
          files: release_assets/*
          body: |
            - Téléchargez le ZIP
            - Extrayez-le
            - Lancez `biduleur.exe`
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
