name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Numéro de version (ex: 1.0.0)'
        required: true
        default: '1.0.0'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'  # Version correspondante à votre environnement local

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Find Python DLL
      id: find_dll
      shell: python
      run: |
        import os
        import sys
        import glob
        dll_path = glob.glob(f"{sys.prefix}/python*.dll")[0]
        print(f"::set-output name=dll_path::{dll_path}")

    - name: Build executable
      run: |
        pyinstaller biduleur.spec --clean
      env:
        PYINSTALLER_DLL_PATH: ${{ steps.find_dll.outputs.dll_path }}

    - name: Prepare release assets
      run: |
        mkdir release_assets
        copy dist\biduleur.exe release_assets\biduleur-${{ github.event.inputs.version || github.ref_name }}-windows.exe

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: Biduleur ${{ github.event.inputs.version || github.ref_name }}
        tag_name: v${{ github.event.inputs.version || github.ref_name }}
        body: |
          ## Biduleur ${{ github.event.inputs.version || github.ref_name }}
          ### Changements
          - [Liste des changements]
        files: release_assets/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
