name: Build and Release - Biduleur (moulinette)

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Numéro de version (ex: 1.0.0)'
        required: true
        default: '1.0.0'
      publish_release:
        description: 'Publier la release ?'
        required: true
        default: 'true'
        type: choice
        options: ['true','false']

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install build tooling
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install pyinstaller==6.6.0

      - name: Install project dependencies
        run: |
          REM requirements.txt is at the repo root
          pip install -r requirements.txt

      - name: Sanity-check deps
        run: |
          python -c "import sys; print(sys.version)"
          pip show pandas || (echo "pandas not installed" && exit /b 1)
          REM If you use pyarrow via pandas, keep this:
          pip show pyarrow || echo "pyarrow not installed (ok if unused)"

      - name: Build executable with PyInstaller
        run: |
          pyinstaller biduleur.spec --clean --workpath build --distpath dist

      - name: List dist contents (debug)
        run: |
          dir dist
          dir dist\biduleur

      - name: Prepare release assets
        run: |
          mkdir release_assets
          echo "Biduleur v${{ github.event.inputs.version || github.ref_name }}" > dist\biduleur\README.txt
          echo "================================================" >> dist\biduleur\README.txt
          echo "" >> dist\biduleur\README.txt
          echo "Instructions :" >> dist\biduleur\README.txt
          echo "1. Extraire le ZIP" >> dist\biduleur\README.txt
          echo "2. Lancer biduleur.exe" >> dist\biduleur\README.txt
          echo "" >> dist\biduleur\README.txt
          echo "Requis : Windows 10+" >> dist\biduleur\README.txt
          Compress-Archive -Path dist\biduleur\* -DestinationPath release_assets\biduleur-${{ github.event.inputs.version || github.ref_name }}-windows.zip -Force

      - name: Upload artifact (debug)
        uses: actions/upload-artifact@v4
        with:
          name: biduleur-dist
          path: dist/biduleur

      - name: Create Release
        if: ${{ github.event.inputs.publish_release != 'false' && (github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/')) }}
        uses: softprops/action-gh-release@v2
        with:
          name: Biduleur ${{ github.event.inputs.version || github.ref_name }}
          tag_name: ${{ github.event.inputs.version && format('v{0}', github.event.inputs.version) || github.ref_name }}
          body: |
            ## Biduleur ${{ github.event.inputs.version || github.ref_name }}

            **Contenu**
            - `biduleur.exe`
            - `README.txt`

            **Instructions**
            1) Téléchargez le ZIP
            2) Extrayez-le
            3) Lancez `biduleur.exe`
          files: release_assets/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
