name: Build and Release - Biduleur (moulinette)

on:
  push:
    tags:
      - 'v*'  # Déclenche automatiquement quand un tag comme v1.0.0 est poussé
  workflow_dispatch:  # Permet de déclencher manuellement
    inputs:
      version:
        description: 'Numéro de version (ex: 1.0.0)'
        required: true
        default: '1.0.0'
      publish_release:
        description: 'Publier la release ?'
        required: true
        default: 'true'
        type: choice
        options:
        - 'true'
        - 'false'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build executable
      run: |
        pyinstaller biduleur.spec --clean --workpath=build --distpath=dist

    - name: Prepare release assets
      run: |
        mkdir release_assets
        copy dist\biduleur\biduleur.exe release_assets\biduleur-${{ github.event.inputs.version || github.ref_name }}-windows.exe

    - name: Create Release
      if: ${{ github.event.inputs.publish_release != 'false' && (github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/')) }}
      uses: softprops/action-gh-release@v1
      with:
        name: Biduleur ${{ github.event.inputs.version || github.ref_name }}
        tag_name: ${{ github.event.inputs.version && format('v{0}', github.event.inputs.version) || github.ref_name }}
        body: |
          ## Biduleur ${{ github.event.inputs.version || github.ref_name }}

          ### Changements
          - [Liste des changements pour cette version]

          ### Instructions
          1. Téléchargez `biduleur-${{ github.event.inputs.version || github.ref_name }}-windows.exe`
          2. Exécutez le fichier (aucune installation nécessaire)
        files: release_assets/*
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
