name: Run Python Script Daily

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: "30 12 * * *"
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" # Specify your Python version

      # Install Dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Set Up Environment
      - name: Set Up Environment
        env:
          INSTAGRAM_USERNAME: ${{ secrets.INSTAGRAM_USERNAME }}
          INSTAGRAM_PASSWORD: ${{ secrets.INSTAGRAM_PASSWORD }}
          INSTAGRAM_VERIFICATION_CODE: ${{ secrets.INSTAGRAM_VERIFICATION_CODE }}
        run: echo "Environment variables set."

      # Run the Script
      - name: Run Script
        run: python main.py True
