name: Run Python Script Daily

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: "0 30 12 * *"
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8" # Specify your Python version

      # Install Dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run the Script
      - name: Run Script
        run: python main.py True
